### ISSUE TITLE
Controleren welke branch naar nieuwe LZ deployed en rechttrekken als nodig

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/tribe-brp-linker#258]
De tribe-omgevingen zijn (even geleden) verhuisd. De inrichting is nu:
- acceptance-new-lz gaat naar nieuwe acceptatie-omgeving
- main-new-lz gaat naar nieuwe prod-omgeving
- acceptance gaat nergens meer heen
- main gaat nergens meer heen.

```[tasklist]
### Tasks
- [x] main.ts aanpassen en voor acceptance-new-lz en acceptance allebei naar nieuwe LZ uitroll
- [x] acceptance-new lz in acceptance mergen
- [x] acceptance-new-lz uitrollen met pipeline die naar acceptance luistert
- [x] prod zelfde acties
- [x] opruimen oude branches
```

**Comment by joostvanderborg** [comment]
acceptance gaat weer naar nieuw LZ, main naar prod in nieuwe LZ. Oude branches opgeruimd.
